import styled from 'styled-components';

export const StyledLoader = styled.img`
<div class="loadingio-spinner-bars-ywuos1rqvrm"><div class="ldio-czkti5culmd">
<div></div><div></div><div></div><div></div>
</div></div>
<style type="text/css">
@keyframes ldio-czkti5culmd {
  0% { opacity: 1 }
  50% { opacity: .5 }
  100% { opacity: 1 }
}
.ldio-czkti5culmd div {
  position: absolute;
  width: 20px;
  height: 80px;
  top: 60px;
  animation: ldio-czkti5culmd 1s cubic-bezier(0.5,0,0.5,1) infinite;
}.ldio-czkti5culmd div:nth-child(1) {
  transform: translate(30px,0);
  background: #251d18;
  animation-delay: -0.6s;
}.ldio-czkti5culmd div:nth-child(2) {
  transform: translate(70px,0);
  background: #402f21;
  animation-delay: -0.4s;
}.ldio-czkti5culmd div:nth-child(3) {
  transform: translate(110px,0);
  background: #5a452e;
  animation-delay: -0.2s;
}.ldio-czkti5culmd div:nth-child(4) {
  transform: translate(150px,0);
  background: #72593d;
  animation-delay: -1s;
}
.loadingio-spinner-bars-ywuos1rqvrm {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-czkti5culmd {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-czkti5culmd div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>`;
